--1. DDL
--1-1. 다른 테이블 참조하여 테이블 생성
CREATE TABLE COURSE_PROFESSOR(CNO, CNAME, PNO, PNAME, AVGRES)
    AS SELECT CNO --NULL값 빼고, INNER로 조인!
            , C.CNAME --순서는 위와 무조건 동일해야 한다.
            , PNO
            , P.PNAME
            , ROUND(AVG(RESULT), 2)
        FROM COURSE C
        NATURAL JOIN SCORE SC
        NATURAL JOIN PROFESSOR P
        GROUP BY CNO, C.CNAME, PNO, P.PNAME;
        
SELECT *
    FROM COURSE_PROFESSOR;
    
--STUDENT SNO, SNAME, MAJOR, SYEAR, SCORE의 RESULT, SCGRADE의 GRADE 가지는 테이블 생성

--DROP TABLE STUDENT_SCGR;

CREATE TABLE STUDENT_GRADE(SNO, SNAME, MAJOR, SYEAR, RESULT, GRADE)
    AS SELECT SNO
            , ST.SNAME
            , ST.MAJOR
            , ST.SYEAR
            , SC.RESULT
            , GR.GRADE
        FROM STUDENT ST
        NATURAL JOIN SCORE SC
        JOIN SCGRADE GR
        ON SC.RESULT BETWEEN GR.LOSCORE AND GR.HISCORE; --비등가조인

SELECT * FROM STUDENT_GRADE;
   

--DROP TABLE SCORE_GRADE1;

CREATE TABLE SCORE_GRADE(SNO, SNAME, MAJOR, SYEAR, RESULT, GRADE)
    AS SELECT SNO
             , ST.SNAME
             , ST.MAJOR
             , ST.SYEAR
             , SC.RESULT
             , SG.GRADE
            FROM STUDENT ST
            NATURAL JOIN SCORE SC
            JOIN SCGRADE SG
            ON SC.RESULT BETWEEN SG.LOSCORE AND SG.HISCORE;

SELECT * 
    FROM SCORE_GRADE
    ORDER BY SNO, RESULT DESC;
    
--1-2. ALTER
--컬럼을 추가하는 ADD
--EMP_COPY 테이블에 ADDR컬럼 추가
ALTER TABLE EMP_COPY
    ADD ADDR VARCHAR2(50);
    
--컬럼명을 변경하는 RENAME
--EMP_COPY 테이블의 SAL 컬럼을 SALARY 변경
ALTER TABLE EMP_COPY
    RENAME COLUMN SAL TO SALARY;
    
 
--이렇게 해버리면, 사실 SAL 참조하던 쿼리문 다 바꿔야 한다.

--컬럼의 데이터타입을 변경하는 MODIFY
--EMP_COPY 테이블의 ENO컬럼의 데이터타입을 VARCHAR2(4 BYTE) -> VARCHAR2(10)
ALTER TABLE EMP_COPY
    MODIFY ENO VARCHAR2(10); --변경될 타입으로 작성

--구조 확인
DESC EMP_COPY;

--컬럼을 삭제하는 DROP
--EMP_COPY 테이블에 ADDR컬럼 삭제
ALTER TABLE EMP_COPY
    DROP COLUMN ADDR;
    
SELECT *
    FROM EMP_COPY;
    

--1-3. 테이블을 삭제하는 DROP
CREATE TABLE SCORE_COPY
    AS SELECT * FROM SCORE;
    
SELECT * FROM SCORE_COPY;    

--SCORE_COPY 테이블 삭제
DROP TABLE SCORE_COPY;


--TIMESTAMP로 DELETE된 데이터 조회가능. DROP은 살릴 수 없다.
--ENTERPRISE 버전에서는 FLASHBACK이라는 기능으로 DRPO한 테이블 복구 가능.
DELETE FROM EMP_COPY;

SELECT *
    FROM EMP_COPY;


SELECT *
    FROM EMP
    AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '180' MINUTE); --생성시점으로 봐야 한다.

    

SELECT *
    FROM EMP_COPY
    AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '14' MINUTE); --생성시점으로 봐야 한다.

--TIMESTAMP 이용해서 삭제된 데이터 복구
INSERT INTO EMP_COPY
SELECT *
    FROM EMP_COPY
    AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '140' MINUTE); --생성시점으로 봐야 한다.


--1-4. RENAME
RENAME EMP_COPY TO EMP_TEMP;



--1-5. 테이블의 데이터를 모두 삭제하는 TRUNCATE :롤백 등도 다 안먹힘!
TRUNCATE TABLE EMP_TEMP;
--Table EMP_TEMP이(가) 잘렸습니다.

SELECT *
    FROM EMP_TEMP;
        