--1. OUTER JOIN 연습
CREATE TABLE BOARD(
    BOARD_NO NUMBER,
    BOARD_TITLE VARCHAR(50)

);

CREATE TABLE BOARD_FILE(
    BOARD_NO NUMBER,
    FILE_NM VARCHAR(50)
    
);


--INSERT INTO BOARD VALUES(10, 'a');
--INSERT INTO BOARD_FILE VALUES(13, 'a');

SELECT * FROM BOARD;
SELECT * FROM BOARD_FILE;

SELECT A.*
    , NVL(B.FILE_NM, 'no file exist')
    FROM BOARD A
--    INNER JOIN BOARD_FILE B
    LEFT OUTER JOIN BOARD_FILE B
--    RIGHT OUTER JOIN BOARD_FILE B
    ON A.BOARD_NO = B.BOARD_NO;


SELECT A.BOARD_TITLE
    , B.BOARD_NO
    , NVL(A.BOARD_TITLE, 'no file exist')
    , NVL(B.FILE_NM, 'no file exist')
    FROM BOARD A
--    RIGHT OUTER JOIN BOARD_FILE B
    FULL OUTER JOIN BOARD_FILE B
    ON A.BOARD_NO = B.BOARD_NO;

--DELETE FROM BOARD 
--    WHERE BOARD_NO = '10';
        
        
SELECT NVL(A.BOARD_TITLE, 'no file exist') BOARD_TITLE
    , NVL(B.FILE_NM, 'no file exist') BOARD_NO
    FROM BOARD A
--    RIGHT OUTER JOIN BOARD_FILE B
    FULL OUTER JOIN BOARD_FILE B
    ON A.BOARD_NO = B.BOARD_NO;
    

--2. INNER JOIN
--SCORE 테이블의 모든 데이터와 STUDENT 테이블의 학생이름 조회
SELECT SC.*
    , ST.SNAME
    FROM SCORE SC
    INNER JOIN STUDENT ST
    ON SC.SNO = ST.SNO; -- 조건확인
    
    
--모든 사원정보와 부서명 동시에 조회
SELECT EP.*
    , DP.DNAME
    FROM EMP EP
    INNER JOIN DEPT DP
    ON EP.DNO = DP.DNO;
    
